import { Router, type IRouter } from "express";
import authRouter from "./auth";
import articlesRouter from "./articles";
import papersRouter from "./papers";
import categoriesRouter from "./categories";
import searchRouter from "./search";
import newsletterRouter from "./newsletter";
import submissionsRouter from "./submissions";
import adminRouter from "./admin";
import archiveRouter from "./archive";
import savedItemsRouter from "./saved-items";
import uploadsRouter from "./uploads";
import collectionsRouter from "./collections";
import notificationsRouter from "./notifications";
import contactRouter from "./contact";
import mediaRouter from "./media";
import extractUrlRouter from "./extract-url";
import commentsRouter from "./comments";
import backupRouter from "./backup";

const router: IRouter = Router();

router.use(authRouter);
router.use(articlesRouter);
router.use(papersRouter);
router.use(categoriesRouter);
router.use(searchRouter);
router.use(newsletterRouter);
router.use(submissionsRouter);
router.use(adminRouter);
router.use(archiveRouter);
router.use(savedItemsRouter);
router.use(uploadsRouter);
router.use(collectionsRouter);
router.use(notificationsRouter);
router.use(contactRouter);
router.use(mediaRouter);
router.use(extractUrlRouter);
router.use(commentsRouter);
router.use(backupRouter);

export default router;
